title: "Beatboxer"
email: andrew@sig.gy
description: >
  A human-sized drum machine built with a Raspberry Pi, LEDs, and Go
url: "https://sig.gy"
baseurl: "/bbox"
markdown: kramdown
theme: jekyll-theme-dinky
github_username:  siggy
twitter_username: siggy
google_analytics: true
github:
  is_project_page: true
  owner_name: siggy
  owner_url: https://github.com/siggy
  repository_url: https://github.com/siggy/bbox
